### ISSUE TITLE
Need List of supported devices.

### ISSUE THREAD

**Issue by nyxymuffin** [duggerd/SoftwareAuthKeyLoader#1]

**Comment by duggerd** [comment]
I don't have a detailed list of every compatible radio at this time. Motorola SUs have been tested to work, however it should be compatible with any radios supporting the standard P25 link layer keyloading protocol. In general, if the radios claim to work with the Motorola KVL4000, they should work with this utility.

**Comment by nyxymuffin** [comment]
Odd. Well I can contribute to the list of ones that dont work. I've got a EF Johnson 5100 that refused to work.

**Comment by duggerd** [comment]
It wouldn't work in that case as the EFJ 5100 doesn't support P25 radio authentication (link layer authentication).

**Comment by nyxymuffin** [comment]
Coolio
